CREATE TABLE IF NOT EXISTS google_ads_conversion_uploads (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL UNIQUE,
  lead_queue_uuid CHAR(36) NOT NULL,
  source VARCHAR(120) NOT NULL DEFAULT '',
  click_id_type ENUM('gclid','gbraid','wbraid') NOT NULL,
  click_id_value VARCHAR(255) NOT NULL,
  conversion_action_resource VARCHAR(160) NOT NULL,
  conversion_value DECIMAL(10,2) NOT NULL DEFAULT 400.00,
  currency_code CHAR(3) NOT NULL DEFAULT 'EUR',
  order_id VARCHAR(80) NOT NULL,
  consent_state VARCHAR(40) NOT NULL DEFAULT 'unset',
  status ENUM('pending','uploaded','failed','skipped') NOT NULL DEFAULT 'pending',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  last_error TEXT NULL,
  request_json JSON NULL,
  response_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  uploaded_at DATETIME NULL,
  UNIQUE KEY uniq_lead_queue_uuid (lead_queue_uuid),
  INDEX idx_gads_status_attempts_created (status, attempts, created_at),
  INDEX idx_gads_order_id (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
